config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true,
                       length: { minimum: 3, maximum: 25 },
                       uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    length: { maximum: 105 },
                    uniqueness: true,
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:alert] = 'You must be logged in.'
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @messages = Message.all
    @users = User.all
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast 'chatroom_channel', message: message_render(message)
      # redirect_to root_path
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: { message: message })
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: %i[new create]

  def new; end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'You have successfully logged in'
      redirect_to root_path
    else
      flash.now[:error] = 'There was something wrong with your login information'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have successfully logged out'
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = 'You are already logged in'
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update show destroy]
  before_action :require_user, only: %i[edit update]
  before_action :require_same_user, only: %i[edit update destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def def(_new)
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "User successfully created. Welcome #{@user.username} "
      redirect_to root_path
    else
      flash[:error] = 'Something went wrong'
      render 'new'
    end
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = 'User was successfully updated'
      redirect_to @user
    else
      flash[:error] = 'Something went wrong'
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = 'Account and all associated articles successfully deleted.'
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user
      flash[:alert] = ' You can edit your account only.'
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 200 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}/?s=#{options[:size]}"
    image_tag(gravatar_url, alt: user.username, class: 'rounded mx-auto d-block')
  end
end

app/views/chatroom/_chat.html.erb
<div class="chat">
  <div class="chat__contacts col-4">
    <% @users.each do |user| %>
      <div class="chat__contact">
        <div class="chat__contact__avatar">
          <%= gravatar_for user, size: 50 %>
        </div>
        <div class="chat__contact__name">
          <span><%= user.username %></span>
        </div>
      </div>
    <% end %>
  </div>
  <div class="chat__column-right col-8">
    <div id="chatMessages" class="chat__messages">
      <%= render @messages %>
    </div>
    <div class="chat__action">
      <%= form_for(@message, html: {id: "chatForm", class: "chat__action__form", role: "form"}, url: message_path, remote: true) do |f|%>
        <%= f.text_field :body, class: "chat__action__form__input", id: "chatInput" %>
        <%= f.button '<i class="i i-send"></i>'.html_safe, :class => 'chat__action__form__button', id: 'chatSendButton' %>
      <% end %>
    </div>
  </div>
</div>

app/views/chatroom/index.html.erb
<%= javascript_pack_tag 'chat', 'data-turbolinks-track': 'reload' %>
<%= render 'chat' %>

app/views/layouts/_messages.html.erb
<%= javascript_pack_tag 'toast', 'data-turbolinks-track': 'reload' %>
<% flash.each do |message_type, message_content| %>
  <div class="alert alert-<%= message_type %> fullwidth toast ">
    <div class="alert-<%= message_type %>__header"><%= message_type %></div>
    <div class="alert-<%= message_type %>__text"><%= message_content %></div>
    <i class="alert__close i i-close toast__close"></i>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat App</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'partials/header' %>
    <div class="main fullheight container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="chat__message">
  <div class="chat__message__avatar">
    <%= gravatar_for message.user, size: 50 %>
  </div>
  <div class="chat__message__body">
    <span class="chat__message__body__username"> <%= message.user.username %> </span>
    <span class="chat__message__body__text"> <%= message.body %> </span>
  </div>
</div>

app/views/partials/_header.html.erb
<div class="header">
    <div class="navbar">
        <div class="container navbar__container">
            <%= link_to root_path do %>
            <div class="navbar__logo">
                <%= image_tag("icon/icon.png", :alt => "logo")%>
                ChatApp
            </div>
            <% end %>
            <ul class="navbar__nav">
                <li class="navbar__nav__item">
                    <% if logged_in? %>
                    <%= link_to 'Log Out', logout_path, class: "nav-link" %>
                    <% else %>
                    <%= link_to 'Log In', login_path, class: "nav-link" %>
                    <% end %>
                </li>
            </ul>
        </div>
    </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, url: users_path) do |f| %>
  <div class="form-group">
    <%= f.label :username, class: "form-label col-4" %>
    <%= f.text_field :username, class: "form-control col-8" %>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "form-label col-4" %>
    <%= f.email_field :email, class: "form-control col-8"%>
  </div>
  <div class="form-group">
    <%= f.label :password, class: "form-label col-4" %>
    <%= f.password_field :password, class: "form-control col-8" %>
  </div>
  <div class="form-group">
    <%= f.submit("Sign Up", class: "btn btn-blue btn-large") %>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="login__wrapper">
  <div class="login card">
    <div class="row">
      <div class="login__signup col-6">
        <div class="login__signup__header">Sign Up</div>
        <div class="login__signup__text">Or Log in if you already have an account</div>
        <%= link_to "Login", login_path, class: "btn btn-transparent-white login__signup__button" %>
      </div>
      <div class="login__form col-6 ">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>